version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-pokemon-data-flow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gaujra16vp61"
s3_prefix = "sam-pokemon-data-flow"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
